// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError('DefaultFirebaseOptions not configured for linux');
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  // Web options
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2O_bH65qjhzfnzgoIF3veP4mmDKHEHxY',
    authDomain: 'crop-guardian.firebaseapp.com',
    projectId: 'crop-guardian',
    storageBucket: 'crop-guardian.firebasestorage.app',
    messagingSenderId: '921634227003',
    appId: '1:921634227003:web:e8bd6c6e51bf4a3493ed1e',
    measurementId: 'G-H34C7R9V8E',
  );

  // Android options
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx0itMabJIyI5SyMHQ3sx0LrzeYCKCuLk',
    appId: '1:921634227003:android:0cfa7a1ff56acdf593ed1e',
    messagingSenderId: '921634227003',
    projectId: 'crop-guardian',
    storageBucket: 'crop-guardian.firebasestorage.app',
  );

  // iOS options
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbyZ2P-AfVi8tKKTVQLN-L48R-6JglHXM',
    appId: '1:921634227003:ios:50d4e57c2639335593ed1e',
    messagingSenderId: '921634227003',
    projectId: 'crop-guardian',
    storageBucket: 'crop-guardian.firebasestorage.app',
    iosBundleId: 'com.example.cropGuardian',
  );

  // macOS options (same as iOS)
  static const FirebaseOptions macos = ios;

  // Windows options
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2O_bH65qjhzfnzgoIF3veP4mmDKHEHxY',
    authDomain: 'crop-guardian.firebaseapp.com',
    projectId: 'crop-guardian',
    storageBucket: 'crop-guardian.firebasestorage.app',
    messagingSenderId: '921634227003',
    appId: '1:921634227003:web:ea318c0f5c9b4c7a93ed1e',
    measurementId: 'G-DB7XD7FT2B',
  );
}
