"""Add language_preference to Profile model

Revision ID: 92d66ac3e972
Revises: 
Create Date: 2025-09-07 16:05:38.492829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92d66ac3e972'
down_revision = None
branch_labels = None
depends_on = None


# Inside your migration script file (e.g., 92d66ac3e972_....py)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        # First, add the column allowing it to be NULL temporarily
        batch_op.add_column(sa.Column('language_preference', sa.String(length=5), nullable=True))

    # Now, update all existing rows to have the default value 'en'
    op.execute("UPDATE profiles SET language_preference = 'en' WHERE language_preference IS NULL")

    # Finally, alter the column to make it NOT NULL
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.alter_column('language_preference', nullable=False)
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('language_preference')

    # ### end Alembic commands ###
